when:
  - event: tag
    branch: main
clone:
  - name: Checkout
    image: woodpeckerci/plugin-git
    settings:
      path: ./plugin/

steps:
  - name: Build
    image: docker
    commands:
      - docker run --rm -e BUILD_PLUGIN=HhagInquiry -v $(PWD)/plugin/:/var/www/html/custom/plugins/HhagInquiry dockware/dev:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  - name: Create Zip
    image: ubuntu
    commands:
      - cd $(PWD)/plugins
      - zip -r ../HhagInquiry.zip .
      -
  - name: Publish
    image: woodpeckerci/plugin-release
    settings:
        files:
          - HhagInquiry.zip
        api_key:
          from_secret: ACCESS_TOKEN
